# Pipeline module configuration
# Method: GrapeSplat [ours]
# Variant: Affine-normalized voxelization enabled

_target_: grapesplat.module.pipeline.PipelineGrapeSplatBuilder

base_geo:
    ckpt: .shared/projects/facebook/VGGT-1B
    type: vggt # NOTE: [anysplat | dvlt | vggt]

base_sem:
    ckpt: null
    type: dinov3 # NOTE: [dinov3]

cam_ray_decoder:
    _target_: grapesplat.module.pipeline.CamRayDecoderBuilder
    train_strat:
        - _target_: grapesplat.module.pipeline.train.DoRABuilder
          alpha: 64
          dropout: 0.0
          rank: 32
          target:
              - ".*pose_branch\\.fc1"
              - ".*trunk[\\d.]+attn\\.(proj|qkv)"
              - ".*trunk[\\d.]+mlp\\.fc[\\d]"
        - _target_: grapesplat.module.pipeline.train.PartFTBuilder
          grad: true
          target:
              - ".*ls[\\d.]+.*"
              - ".*norm[\\d.]+.*"

depth1_decoder:
    _target_: grapesplat.module.pipeline.Depth1DecoderBuilder
    train_strat:
        - _target_: grapesplat.module.pipeline.train.PartFTBuilder
          grad: true
          target:
              - ".*norm[\\d.]+.*"
              - ".*output_conv1.*"

depth2_image_decoder:
    _target_: grapesplat.module.pipeline.Depth2ImageDecoderBuilder
    antialiased: false
    bgcolor: [1.0, 1.0, 1.0]
    depth_mode: ED
    far: 1e+2
    near: 1e-2
    train_strat:
        - _target_: grapesplat.module.pipeline.train.FullFTBuilder
          grad: false
          target: []

image_encoder:
    _target_: grapesplat.module.pipeline.ImageEncoderBuilder
    geo:
        enabled: true
        train_strat:
            - _target_: grapesplat.module.pipeline.train.DoRABuilder
              alpha: 64
              dropout: 0.0
              rank: 32
              target:
                  - ".*blocks[\\d.]+attn\\.(proj|qkv)"
                  - ".*blocks[\\d.]+mlp\\.fc[\\d]"
            - _target_: grapesplat.module.pipeline.train.PartFTBuilder
              grad: true
              target:
                  - ".*ls[\\d.]+.*"
                  - ".*norm[\\d.]+.*"
    sem:
        dtype:
            _target_: hydra.utils.get_object
            path: torch.bfloat16
        enabled: false
        train_strat:
            - _target_: grapesplat.module.pipeline.train.FullFTBuilder
              grad: false
              target: []

scene_decoder:
    _target_: grapesplat.module.pipeline.SceneDecoderBuilder

    gausshead:
        _target_: grapesplat.module.pipeline.scene_decoder.GaussHeadBuilder
        count: 1
        group:
            - _target_: grapesplat.module.pipeline.scene_decoder.mlp.MLPBuilder
              act: { _target_: torch.nn.Sigmoid }
              block:
                  _target_: grapesplat.module.pipeline.scene_decoder.mlp.MLPBlockBuilder
                  dim_h_base: 128
                  dim_h_mult: 4.0
                  dim_o: 1
              init_bias: -2.0 # NOTE: 12%
              label: opacity

            - _target_: grapesplat.module.pipeline.scene_decoder.mlp.MLPBuilder
              act:
                  _target_: grapesplat.module.pipeline.scene_decoder.code.SHAtt
                  decay: 0.7
              block:
                  _target_: grapesplat.module.pipeline.scene_decoder.mlp.MLPBlockBuilder
                  dim_h_base: 128
                  dim_h_mult: 4.0
                  dim_o: 48 # NOTE: (16, 3)
              init_bias: 0.0 # NOTE: Grayish
              label: color

            - _target_: grapesplat.module.pipeline.scene_decoder.mlp.MLPBuilder
              act: { _target_: torch.nn.Sigmoid }
              block:
                  _target_: grapesplat.module.pipeline.scene_decoder.mlp.MLPBlockBuilder
                  dim_h_base: 128
                  dim_h_mult: 4.0
                  dim_o: 3
              init_bias: 0.0 # NOTE: Centered
              label: pos_local

            - _target_: grapesplat.module.pipeline.scene_decoder.mlp.MLPBuilder
              act: { _target_: grapesplat.module.pipeline.scene_decoder.code.GSO }
              block:
                  _target_: grapesplat.module.pipeline.scene_decoder.mlp.MLPBlockBuilder
                  dim_h_base: 128
                  dim_h_mult: 4.0
                  dim_o: 6 # NOTE: (3, 3)
              init_bias: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0] # NOTE: Identity
              label: rotation

            - _target_: grapesplat.module.pipeline.scene_decoder.mlp.MLPBuilder
              act:
                  _target_: grapesplat.module.pipeline.scene_decoder.code.ExpTanh
                  bound_log: 3.0 # NOTE: [0.05, 20.1]
              block:
                  _target_: grapesplat.module.pipeline.scene_decoder.mlp.MLPBlockBuilder
                  dim_h_base: 128
                  dim_h_mult: 4.0
                  dim_o: 3
              init_bias: 0.0 # NOTE: 1.0
              label: scale_local

    train_strat:
        - _target_: grapesplat.module.pipeline.train.PartFTBuilder
          grad: true
          target: [".*"]

    unet:
        _target_: grapesplat.module.pipeline.scene_decoder.UNetBuilder
        dim_h_base: 128
        dim_h_mult: [1.0, 2.0, 4.0, 4.0] # NOTE: [L0, L1, L2, Lb]
        spconv:
            _target_: grapesplat.module.pipeline.scene_decoder.unet.UNetSpConvStrategy
            depth: 2
            dim_h_mult: 4.0
            kernel: 3

    voxelize:
        _target_: grapesplat.module.pipeline.scene_decoder.VoxelizeBuilder
        dim_h_base: 128
        dim_h_mult: 4.0
        feat_bridge:
            _target_: grapesplat.module.pipeline.scene_decoder.FeatBridgeBuilder
            geo:
                enabled: true
                train_strat:
                    - _target_: grapesplat.module.pipeline.train.FullFTBuilder
                      grad: true
                      target: []
            sem:
                enabled: false
                train_strat:
                    - _target_: grapesplat.module.pipeline.train.FullFTBuilder
                      grad: false
                      target: []
        grid_resol: 448
        peach: false
        spe_depth_log:
            _target_: grapesplat.module.pipeline.scene_decoder.code.SPEBuilder
            band: 5
        spe_image:
            _target_: grapesplat.module.pipeline.scene_decoder.code.SPEBuilder
            band: 6
        spe_pos_local:
            _target_: grapesplat.module.pipeline.scene_decoder.code.SPEBuilder
            band: 5
        spe_pos_world:
            _target_: grapesplat.module.pipeline.scene_decoder.code.SPEBuilder
            band: null
        spe_ray:
            _target_: grapesplat.module.pipeline.scene_decoder.code.SPEBuilder
            band: 4
        voxel_count_train_max: 600000

scene_optimizer:
    _target_: grapesplat.module.pipeline.SceneOptimizerBuilder
    enabled: false
    loss:
        type: l1
        weight: 1.0
    optimizer:
        _target_: grapesplat.module.optimizer.CompositeOptimizerBuilder
        group:
            - lr: 5e-3
              params: color
              weight_decay: 0.0
            - lr: 5e-3
              params: opacity
              weight_decay: 0.0
            - lr: 0.0
              params: position
              weight_decay: 0.0
            - lr: 0.0
              params: shape
              weight_decay: 0.0
        type: adam_w
    scheduler:
        _target_: grapesplat.module.scheduler.CompositeSchedulerBuilder
        lr_decay_min: 1e-4
        lr_warmup_iters_pr: 0.0
    step: 128

testing: false
