# Optimizer module configuration

_target_: grapesplat.module.optimizer.CompositeOptimizerBuilder

group:
    - lr: 1e-4
      params: cam_ray_decoder
      weight_decay: 0.02
    - lr: 1e-4
      params: depth1_decoder
      weight_decay: 0.02
    - lr: 1e-4
      params: image_encoder
      weight_decay: 0.02
    - lr: 5e-5
      params: scene_decoder
      weight_decay: 0.04
type: adam_w
